# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Visualizing the Future Symposia
tagline:          'A National Forum on Data Visualization in Libraries'
description:      'A National Forum on Data Visualization in Libraries'
url:              http://hyde.getpoole.com
baseurl:          https://visualizingthefuture.github.io/

author:
  name:           'Visualizing the Future'
  url:            https://visualizingthefuture.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/visualizingthefuture/visualizingthefuture.github.io
